SET SERVEROUTPUT ON;

EXEC PRC_REG_LOOKUP('ST001','A-FS001');
EXEC PRC_AD_REG_LOOKUP;

SELECT *
FROM VIEW_OC;
SELECT MIN(ROWNUM),MAX(ROWNUM)
    FROM VIEW_OC;
SELECT *
FROM TBL_REG;
SELECT *
                FROM TBL_SC;
                WHERE REG_CD = 'RG001' AND OS_CD = 'A-O001';
SELECT OS_CD,SUB_CD
                FROM VIEW_OS
                WHERE OC_CD = 'A-FS001' AND NUM_OS = 2;
SELECT *
FROM TBL_ST;

UPDATE TBL_ST
SET ST_FN = '김', ST_LN = '아별'
WHERE ST_ID='ST001';

ALTER TABLE TBL_ST MODIFY(ST_LN VARCHAR2(50));

SELECT *
FROM VIEW_OS_ORDER;
SELECT *
FROM TBL_REG;
WHERE NUM_OC = 2;
SELECT MAX(ROWNUM)
        FROM TBL_REG
        WHERE OC_CD = 'A-FS001';

 SELECT ST_ID 
            FROM VIEW_REG_ORDER
            WHERE NUM_REG_ORDER = 1;
            
            SELECT REG_CD 
                FROM VIEW_REG_ORDER
                WHERE ST_ID = 'ST001' AND NUM_REG_ORDER = 1;
                
                SELECT SUB_CD
                FROM VIEW_OS
                WHERE OC_CD = 'A-FS001' AND NUM_OS = 1;
                SELECT *
                FROM TBL_SC;
EXEC PRC_REG_LOOKUP('ST002','A-FS001');
SELECT *
FROM TBL_REG;
SELECT COUNT(*) 
    FROM TBL_REG
    WHERE ST_ID = 'ST002' AND OC_CD = 'A-FS001';
/*
ST001 A-FS001
ST002 A-FS001
ST003 A-FS001
ST004 A-FS001
ST005 A-FS001
ST001 A-WE001
*/
SELECT REG_CD 
                FROM TBL_REG
                WHERE ST_ID = 'ST001';
    
CREATE OR REPLACE VIEW VIEW_OC
AS
SELECT T.*
FROM
(   SELECT ROWNUM "NUM_OC", OC_CD "OC_CD", CRS_CD "CRS_CD", CRS_BD "CRS_BD", CRS_ED "CRS_ED", CRS_RM "CRS_RM"
    FROM TBL_OC
	ORDER BY 2
)T;
        SELECT *
        FROM VIEW_REG_ORDER
        WHERE ST_ID = 'ST001';
            SELECT *
            FROM TBL_OC
            WHERE OC_CD = 'A-WE001';
            SELECT *
            FROM TBL_REG
            WHERE ST_ID = 'ST001';
            
                SELECT COUNT(*)
		        FROM TBL_QT
		        WHERE REG_CD = 'RG001';
            
            SELECT MIN(ROWNUM),MAX(ROWNUM)
            FROM TBL_REG
            WHERE ST_ID = 'ST002';
            
                SELECT OC_CD, REG_CD
                FROM TBL_REG
                WHERE ST_ID = 'ST002';

EXEC PRC_REG_ST_LOOKUP('ST001','RG003','A-H001');
EXEC PRC_REG_ST_LOOKUP_ALL('ST001');

SELECT OC_CD FROM TBL_REG WHERE REG_CD = 'RG003';

SELECT REG_CD,OC_CD
        FROM VIEW_REG_ORDER
        WHERE NUM_REG_ORDER = 2;
SELECT *
FROM TBL_OS;
SELECT *
FROM TBL_SC;
WHERE NUM_OS = 3;
/*
NUM_OS_ORDER	NUM_OS	OS_CD	OC_CD	SUB_CD	PR_ID	BK_CD	RAT_CD	SUB_BD	SUB_ED
4	            3	    A-W001	A-WE001	W001	PR001	B002	RT001	21/03/01	21/03/15
*/
            SELECT SC_CD
            FROM TBL_SC
            WHERE REG_CD = 'RG006' AND OS_CD = 'A-W001';
            
            SELECT *
            FROM VIEW_OS_ORDER;
            WHERE NUM_OS_ORDER = V_START_OS;
SELECT *
FROM TBL_SC;

        SELECT *
        FROM VIEW_OS_ORDER
        WHERE OC_CD = 'A-FS001';
        
        SELECT MIN(ROWNUM),MAX(ROWNUM)
        FROM VIEW_OS_ORDER
        WHERE OC_CD = 'A-WE001' AND SYSDATE - SUB_ED > 0;
        
                    SELECT OS_CD 
            FROM VIEW_OS_ORDER
            WHERE NUM_OS_ORDER = 1;
            
            SELECT SC_CD 
            FROM TBL_SC
            WHERE REG_CD = 'RG006';

        SELECT *
        FROM VIEW_OS_ORDER;
        WHERE NUM_OS = 2;
        
            SELECT SUB_CD
    FROM VIEW_OS
    WHERE OS_CD = 'A-O001';
    
        SELECT MIN(ROWNUM),MAX(ROWNUM)
        FROM VIEW_OS_ORDER
        WHERE OC_CD = 'A-FS001';
        
            SELECT *
        FROM VIEW_OS;
        
        SELECT *
    FROM VIEW_OS
    WHERE OC_CD = 'A-FS001' AND OS_CD = 'A-J001';
    
        SELECT REG_CD 
        FROM VIEW_REG_ORDER
        WHERE NUM_REG_ORDER = 2;
        
    SELECT *
    FROM VIEW_OS_ORDER;
    WHERE OC_CD = 'A-FS001';
        
    SELECT *
    FROM VIEW_OS;
    WHERE OC_CD = 'A-WE001' AND NUM_OS = 2;
    
        SELECT * 
    FROM TBL_SC;
        
        SELECT REG_CD 
        FROM VIEW_REG_ORDER
        WHERE NUM_REG_ORDER = 1;
        
    SELECT OC_CD
    FROM TBL_REG
    WHERE REG_CD = 'RG003';
    
    SELECT SUB_CD
    FROM VIEW_OS
    WHERE OC_CD = 'A-FS001' AND NUM_OS = 2;
    
        SELECT REG_CD
        FROM VIEW_REG_ORDER
        WHERE NUM_REG_ORDER = 2;

    SELECT MIN(ROWNUM),MAX(ROWNUM)
    FROM VIEW_REG_ORDER
    WHERE ST_ID = 'ST001';
    
            SELECT OS_CD 
        FROM VIEW_OS_ORDER
        WHERE NUM_OS_ORDER = 2;
        
        
SELECT *
FROM TBL_OS;

INSERT INTO TBL_SC(SC_CD,REG_CD,OS_CD,SC_AT,SC_WT,SC_PT)
VALUES('SC006','RG003','A-H001',10,10,10);

SELECT *
FROM USER_OBJECTS
WHERE OBJECT_NAME LIKE 'VIEW%';

SELECT *
FROM TBL_SUB;

INSERT INTO TBL_SUB(SUB_CD,SUB_NM) VALUES('H001','H HTML');

SELECT *
FROM TBL_OS;

INSERT INTO TBL_OS(OS_CD,OC_CD,SUB_CD,PR_ID,BK_CD,RAT_CD,SUB_BD,SUB_ED)
VALUES('A-H001','A-FS001','H001','PR001','B001','RT001','21/03/17','21/03/20');

SELECT *
FROM VIEW_OS;

SELECT *
FROM VIEW_REG_ORDER;

SELECT *
FROM TBL_OC;

INSERT INTO TBL_OC(OC_CD,CRS_CD,CRS_BD,CRS_ED,CRS_RM)
VALUES('A-WE001','WE001','21/03/01','21/08/01','E강의실');

SELECT *
FROM VIEW_REG;

SELECT *
FROM TBL_QT;

SELECT *
FROM TBL_CRS;

INSERT INTO TBL_CRS(CRS_CD,CRS_NM) VALUES('WE001','WE 웹개발');

SELECT *
FROM TBL_REG;

INSERT INTO TBL_REG(REG_CD,ST_ID,OC_CD,REG_DT) VALUES('RG007','ST001','A-FS001','21/02/01');

SELECT *
FROM VIEW_REG;

CREATE OR REPLACE VIEW VIEW_REG_ORDER
AS
SELECT T.*
FROM
(   SELECT ROWNUM "NUM_REG_ORDER", REG_CD "REG_CD", ST_ID "ST_ID", OC_CD "OC_CD", REG_DT "REG_DT"
    FROM VIEW_REG
)T;

CREATE OR REPLACE VIEW VIEW_OS
AS
SELECT T.*
FROM
(   SELECT ROWNUM "NUM_OS", OS_CD "OS_CD", OC_CD "OC_CD", SUB_CD "SUB_CD", PR_ID "PR_ID"
         , BK_CD "BK_CD", RAT_CD "RAT_CD", SUB_BD "SUB_BD", SUB_ED "SUB_ED"
    FROM TBL_OS
    ORDER BY 3; 
)T;

CREATE OR REPLACE VIEW VIEW_OS
AS
SELECT T.*
FROM
(   SELECT ROWNUM "NUM_OS", OS_CD "OS_CD", OC_CD "OC_CD", SUB_CD "SUB_CD", PR_ID "PR_ID"
         , BK_CD "BK_CD", RAT_CD "RAT_CD", SUB_BD "SUB_BD", SUB_ED "SUB_ED"
    FROM TBL_OS
    ORDER BY 3
)T;

CREATE OR REPLACE VIEW VIEW_OS_ORDER
AS
SELECT T.*
FROM
(   SELECT ROWNUM "NUM_OS_ORDER", NUM_OS "NUM_OS", OS_CD "OS_CD", OC_CD "OC_CD", SUB_CD "SUB_CD", PR_ID "PR_ID"
         , BK_CD "BK_CD", RAT_CD "RAT_CD", SUB_BD "SUB_BD", SUB_ED "SUB_ED"
    FROM VIEW_OS
)T;